### ISSUE TITLE
Printing statement Error

### ISSUE THREAD

**Issue by huangs1** [lussierc/simplePerformanceExperimentsJava#2]
After the user has entered in the 'suggested campaign length" the user is then prompt to choose which data type they would like to choose; there are two grammatical errors. It current prints ```What kind of datatype do uwant to test?``` I believe you all wanted to print out ```What kind of data type do you want to test?```

**Comment by Lancasterwu** [comment]
Thanks very much for noticing that! You are absolutely right, and that is what we wanted to print out.

**Comment by lussierc** [comment]
@huangs1 Hi thanks for noticing this issue!

**Comment by lussierc** [comment]
I have merged the pull request that fixes this typo and as a result, I am closing this issue.
